### ISSUE TITLE
PARA!

### ISSUE THREAD

**Issue by andrscyv** [Alex23rodriguez/Amazons#1]
No aprendas React, Vue es mejor

**Comment by andrscyv** [comment]
PELAMEEEE

**Comment by andrscyv** [comment]
puedes usar esto https://boardgame.io/

**Comment by Alex23rodriguez** [comment]
Te invito a darme clases de Vue, o forkear el proyecto para ver qué onda 👍 
Lo de boardgame se ve interesante, pero creo que para este proyecto es un poco overkill. Te aviso cuando planee hacer el próximo Catan ;)
